/* dtool_config.h.  Generated automatically by makepanda.py */
#define COMPILE_IN_DEFAULT_FONT 1
#undef DEBUG_THREADS
#define DEFAULT_PATHSEP ";"
#define DO_COLLISION_RECORDING 1
#define DO_DCAST 1
#define DO_MEMORY_USAGE 1
#define DO_PIPELINING 1
#define DO_PSTATS 1
#undef GETTIMEOFDAY_ONE_PARAM
#define GLOBAL_ARGC __argc
#define GLOBAL_ARGV __argv
#define HAVE_ARTOOLKIT 1
#define HAVE_AUDIO 1
#define HAVE_BMP 1
#define HAVE_CG 1
#define HAVE_CGDX9 1
#define HAVE_CGGL 1
#undef HAVE_COCOA
#undef HAVE_DINKUM
#undef HAVE_DIRECTCAM
#undef HAVE_DX9
#undef HAVE_EIGEN
#undef HAVE_FFTW
#define HAVE_FREETYPE 1
#undef HAVE_GETOPT
#undef HAVE_GETOPT_LONG_ONLY
#define HAVE_GLOBAL_ARGV 1
#undef HAVE_GLX
#define HAVE_IMG 1
#define HAVE_IOS_BINARY 1
#define HAVE_IOS_TYPEDEFS 1
#define HAVE_JPEG 1
#define HAVE_MAYA 1
#define HAVE_NET 1
#undef HAVE_OPENAL_FRAMEWORK
#define HAVE_OPENEXR 1
#define HAVE_OPENSSL 1
#define HAVE_OPUS 1
#undef HAVE_P3D_PLUGIN
#define HAVE_PNG 1
#define HAVE_PNM 1
#undef HAVE_POSIX_THREADS
#undef HAVE_PROC_CURPROC_FILE
#undef HAVE_PROC_CURPROC_MAP
#undef HAVE_PROC_SELF_CMDLINE
#undef HAVE_PROC_SELF_ENVIRON
#undef HAVE_PROC_SELF_EXE
#undef HAVE_PROC_SELF_MAPS
#define HAVE_PYTHON 1
#define HAVE_ROCKET_DEBUGGER 1
#define HAVE_ROCKET_PYTHON 1
#define HAVE_RTTI 1
#define HAVE_SGI_RGB 1
#define HAVE_SOFTIMAGE_PIC 1
#define HAVE_SQUISH 1
#define HAVE_STB_IMAGE 1
#undef HAVE_STL_HASH
#define HAVE_TGA 1
#define HAVE_THREADS 1
#define HAVE_TIFF 1
#undef HAVE_VIDEO4LINUX
#define HAVE_VORBIS 1
#define HAVE_WGL 1
#undef HAVE_X11
#define HAVE_ZLIB 1
#undef IOCTL_TERMINAL_WIDTH
#undef IS_FREEBSD
#undef IS_LINUX
#undef IS_OSX
#define LINMATH_ALIGN 1
#undef MUTEX_SPINLOCK
#define NOTIFY_DEBUG 1
#define OS_SIMPLE_THREADS 1
#undef PHAVE_ALLOCA_H
#undef PHAVE_DIRENT_H
#undef PHAVE_GETOPT_H
#undef PHAVE_GLOB_H
#define PHAVE_IOSTREAM 1
#define PHAVE_IO_H 1
#undef PHAVE_LIMITS_H
#undef PHAVE_LINUX_INPUT_H
#undef PHAVE_LOCALE_H
#define PHAVE_LOCKF 1
#define PHAVE_MALLOC_H 1
#define PHAVE_NEW 1
#define PHAVE_SSTREAM 1
#define PHAVE_STDINT_H 1
#undef PHAVE_STDLIB_H
#undef PHAVE_STRING_H
#undef PHAVE_SYS_MALLOC_H
#undef PHAVE_SYS_TIME_H
#define PHAVE_SYS_TYPES_H 1
#undef PHAVE_UCONTEXT_H
#undef PHAVE_UNISTD_H
#undef PHAVE_UTIME_H
#define PRC_SAVE_DESCRIPTIONS 1
#undef PROTOTYPE_GLOBAL_ARGV
#undef PYTHON_FRAMEWORK
#define REPORT_OPENSSL_ERRORS 1
#define SIMPLE_STRUCT_POINTERS 1
#undef SIMPLE_THREADS
#undef SIMULATE_NETWORK_DELAY
#define STATIC_INIT_GETENV 1
#undef STDFLOAT_DOUBLE
#define SUPPORT_FIXED_FUNCTION 1
#undef SUPPORT_IMMEDIATE_MODE
#undef USE_DEBUG_PYTHON
#define USE_DELETED_CHAIN 1
#undef USE_GENERIC_DXERR_LIBRARY
#define USE_PANDAFILESTREAM 1
#undef USE_TAU
#define WANT_NATIVE_NET 1
#undef WORDS_BIGENDIAN
