
#define PANDA_MAJOR_VERSION 1
#define PANDA_MINOR_VERSION 11
#define PANDA_SEQUENCE_VERSION 0
#define PANDA_VERSION 1010999
#define PANDA_NUMERIC_VERSION 1010999
#define PANDA_VERSION_STR "1.11.0"
#define PANDA_ABI_VERSION_STR "1.11"
#define PANDA_DISTRIBUTOR "Gustavo"
#define PANDA_PACKAGE_VERSION_STR "Gustavo_1.11"
#define PANDA_PACKAGE_HOST_URL ""

#undef  PANDA_OFFICIAL_VERSION
