from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_12/models/bossbotHQ/BossbotEntranceRoom',
        'wantDoors': 1},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10000: {'type': 'entrancePoint',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 6, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'entranceId': 0,
         'radius': 15,
         'theta': 20},
 110600: {'type': 'battleBlocker',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(8.046, -30.702, 0),
          'hpr': Point3(270, 0, 0),
          'scale': Vec3(1, 1, 1),
          'cellId': 0,
          'radius': 10},
 10002: {'type': 'nodepath',
         'name': 'props',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10041: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, -20, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 0,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10042: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, -16, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 1,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10043: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, -12, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 2,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10044: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, -8, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 3,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10045: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, 4, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 4,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10046: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, 8, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 5,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10047: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, 12, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 6,
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10048: {'type': 'healBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-21.655, 16, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': 1,
         'rewardPerGrab': 200,
         'rewardPerGrabMax': 0}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
