from SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 110200
CogParent1 = 110300
CogParent2 = 110301
CogParent3 = 110302
CogParent4 = 110303
CogParent5 = 110304
CogParent6 = 110305
CogParent7 = 110306
CogParent8 = 110307
CogParent9 = 110308
CogParent10 = 110309
CogParent11 = 110310
CogParent12 = 110311
CogParent13 = 110312
BattleCellId = 0
Battle1CellId = 1
Battle2CellId = 2
Battle3CellId = 3
Battle4CellId = 4
Battle5CellId = 5
Battle6CellId = 6
Battle7CellId = 7
Battle8CellId = 8
Battle9CellId = 9
Battle10CellId = 10
Battle11CellId = 11
Battle12CellId = 12
Battle13CellId = 13
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
Battle1CellId: {'parentEntId': CogParent1,
                'pos': Point3(0, 0, 0)},
Battle2CellId: {'parentEntId': CogParent2,
                'pos': Point3(0, 0, 0)},
Battle3CellId: {'parentEntId': CogParent3,
                'pos': Point3(0, 0, 0)},
Battle4CellId: {'parentEntId': CogParent4,
                'pos': Point3(0, 0, 0)},
Battle5CellId: {'parentEntId': CogParent5,
                'pos': Point3(0, 0, 0)},
Battle6CellId: {'parentEntId': CogParent6,
                'pos': Point3(0, 0, 0)},
Battle7CellId: {'parentEntId': CogParent7,
                'pos': Point3(0, 0, 0)},
Battle8CellId: {'parentEntId': CogParent8,
                'pos': Point3(0, 0, 0)},
Battle9CellId: {'parentEntId': CogParent9,
                'pos': Point3(0, 0, 0)},
Battle10CellId: {'parentEntId': CogParent10,
                'pos': Point3(0, 0, 0)},
Battle11CellId: {'parentEntId': CogParent11,
                'pos': Point3(0, 0, 0)},
Battle12CellId: {'parentEntId': CogParent12,
                'pos': Point3(0, 0, 0)},
Battle13CellId: {'parentEntId': CogParent13,
                'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Battle1CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Battle1CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Battle1CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Battle1CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent2,
  'boss': 0,
  'level': 10,
  'battleCell': Battle2CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': 11,
  'battleCell': Battle2CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': 10,
  'battleCell': Battle2CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': 11,
  'battleCell': Battle2CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent3,
  'boss': 0,
  'level': 10,
  'battleCell': Battle3CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent3,
  'boss': 0,
  'level': 10,
  'battleCell': Battle3CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent3,
  'boss': 0,
  'level': 11,
  'battleCell': Battle3CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent3,
  'boss': 0,
  'level': 10,
  'battleCell': Battle3CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': CogParent4,
  'boss': 0,
  'level': 10,
  'battleCell': Battle4CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent4,
  'boss': 0,
  'level': 10,
  'battleCell': Battle4CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent4,
  'boss': 0,
  'level': 10,
  'battleCell': Battle4CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent4,
  'boss': 0,
  'level': 10,
  'battleCell': Battle4CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent5,
  'boss': 0,
  'level': 10,
  'battleCell': Battle5CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent5,
  'boss': 0,
  'level': 10,
  'battleCell': Battle5CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent5,
  'boss': 0,
  'level': 10,
  'battleCell': Battle5CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent5,
  'boss': 0,
  'level': 10,
  'battleCell': Battle5CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent6,
  'boss': 0,
  'level': 10,
  'battleCell': Battle6CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent6,
  'boss': 0,
  'level': 10,
  'battleCell': Battle6CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent6,
  'boss': 0,
  'level': 10,
  'battleCell': Battle6CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent6,
  'boss': 0,
  'level': 10,
  'battleCell': Battle6CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent7,
  'boss': 0,
  'level': 10,
  'battleCell': Battle7CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent7,
  'boss': 0,
  'level': 10,
  'battleCell': Battle7CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent7,
  'boss': 0,
  'level': 10,
  'battleCell': Battle7CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent7,
  'boss': 0,
  'level': 10,
  'battleCell': Battle7CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent8,
  'boss': 0,
  'level': 10,
  'battleCell': Battle8CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent8,
  'boss': 0,
  'level': 10,
  'battleCell': Battle8CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent8,
  'boss': 0,
  'level': 10,
  'battleCell': Battle8CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent8,
  'boss': 0,
  'level': 10,
  'battleCell': Battle8CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent9,
  'boss': 0,
  'level': 10,
  'battleCell': Battle9CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent9,
  'boss': 0,
  'level': 10,
  'battleCell': Battle9CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent9,
  'boss': 0,
  'level': 10,
  'battleCell': Battle9CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent9,
  'boss': 0,
  'level': 10,
  'battleCell': Battle9CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': CogParent10,
  'boss': 0,
  'level': 10,
  'battleCell': Battle10CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent10,
  'boss': 0,
  'level': 11,
  'battleCell': Battle10CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent10,
  'boss': 0,
  'level': 10,
  'battleCell': Battle10CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent10,
  'boss': 0,
  'level': 11,
  'battleCell': Battle10CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent11,
  'boss': 0,
  'level': 10,
  'battleCell': Battle11CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent11,
  'boss': 0,
  'level': 10,
  'battleCell': Battle11CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent11,
  'boss': 0,
  'level': 10,
  'battleCell': Battle11CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent11,
  'boss': 0,
  'level': 10,
  'battleCell': Battle11CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': CogParent12,
  'boss': 0,
  'level': 10,
  'battleCell': Battle12CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent12,
  'boss': 0,
  'level': 10,
  'battleCell': Battle12CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent12,
  'boss': 0,
  'level': 10,
  'battleCell': Battle12CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent12,
  'boss': 0,
  'level': 10,
  'battleCell': Battle12CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent13,
  'boss': 0,
  'level': 10,
  'battleCell': Battle13CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent13,
  'boss': 0,
  'level': 10,
  'battleCell': Battle13CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent13,
  'boss': 0,
  'level': 10,
  'battleCell': Battle13CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent13,
  'boss': 0,
  'level': 10,
  'battleCell': Battle13CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]
ReserveCogData = []
