from .SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 10000
CogParent1 = 10001
CogParent2 = 10002
BattleCellId = 0
Battle2CellId = 1
Battle3CellId = 2
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
 Battle2CellId: {'parentEntId': CogParent1,
                'pos': Point3(0, 0, 0)},
 Battle3CellId: {'parentEntId': CogParent2,
                'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'dm',
  'parentEntId': CogParent,
  'boss': 1,
  'level': 35,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 21,
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': CogParent1,
  'boss': 0,
  'level': 10,
  'battleCell': Battle2CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Battle2CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': 10,
  'battleCell': Battle2CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Battle2CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': CogParent2,
  'boss': 0,
  'level': 13,
  'battleCell': Battle3CellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': 11,
  'battleCell': Battle3CellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': 11,
  'battleCell': Battle3CellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent2,
  'boss': 0,
  'level': 11,
  'battleCell': Battle3CellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}]
ReserveCogData = []
