from SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 10000
FrontCogParent = 10001
FrontCogParent1 = 10002
FrontCogParent2 = 10005
SideCogParent = 10006
SideCogParent1 = 10007
SideCogParent2 = 10008
SideCogParent3 = 10009
BattleCellId = 0
FrontBattleCellId = 1
Front1BattleCellId = 2
Front2BattleCellId = 3
SideBattleCellId = 4
Side1BattleCellId = 5
Side2BattleCellId = 6
Side3BattleCellId = 7
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
 FrontBattleCellId: {'parentEntId': FrontCogParent,
                   'pos': Point3(0, 0, 0)},
 Front1BattleCellId: {'parentEntId': FrontCogParent1,
                 'pos': Point3(0, 0, 0)},
 Front2BattleCellId: {'parentEntId': FrontCogParent2,
                 'pos': Point3(0, 0, 0)},
 SideBattleCellId: {'parentEntId': SideCogParent,
                   'pos': Point3(0, 0, 0)},
 Side1BattleCellId: {'parentEntId': SideCogParent1,
                   'pos': Point3(0, 0, 0)},
 Side2BattleCellId: {'parentEntId': SideCogParent2,
                   'pos': Point3(0, 0, 0)},
 Side3BattleCellId: {'parentEntId': SideCogParent3,
                   'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'dm',
  'parentEntId': CogParent,
  'boss': 1,
  'level': 35,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'csh',
  'parentEntId': CogParent,
  'boss': 0,
  'level': 23,
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'bgr',
  'parentEntId': CogParent,
  'boss': 0,
  'level': 26,
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mes',
  'parentEntId': CogParent,
  'boss': 0,
  'level': 31,
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 12,
  'battleCell': FrontBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 12,
  'battleCell': FrontBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 12,
  'battleCell': FrontBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 12,
  'battleCell': FrontBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
{'parentEntId': FrontCogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Front1BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': FrontCogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Front1BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Front1BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': FrontCogParent1,
  'boss': 0,
  'level': 11,
  'battleCell': Front1BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': 10,
  'battleCell': Front2BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': 10,
  'battleCell': Front2BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': 10,
  'battleCell': Front2BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent2,
  'boss': 0,
  'level': 10,
  'battleCell': Front2BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': SideCogParent,
  'boss': 0,
  'level': 13,
  'battleCell': SideBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent,
  'boss': 0,
  'level': 13,
  'battleCell': SideBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent,
  'boss': 0,
  'level': 13,
  'battleCell': SideBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent,
  'boss': 0,
  'level': 13,
  'battleCell': SideBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': SideCogParent1,
  'boss': 0,
  'level': 16,
  'battleCell': Side1BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent1,
  'boss': 0,
  'level': 16,
  'battleCell': Side1BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent1,
  'boss': 0,
  'level': 16,
  'battleCell': Side1BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent1,
  'boss': 0,
  'level': 16,
  'battleCell': Side1BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': SideCogParent2,
  'boss': 0,
  'level': 14,
  'battleCell': Side2BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent2,
  'boss': 0,
  'level': 14,
  'battleCell': Side2BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent2,
  'boss': 0,
  'level': 14,
  'battleCell': Side2BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent2,
  'boss': 0,
  'level': 14,
  'battleCell': Side2BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': SideCogParent3,
  'boss': 0,
  'level': 15,
  'battleCell': Side3BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent3,
  'boss': 0,
  'level': 15,
  'battleCell': Side3BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent3,
  'boss': 0,
  'level': 15,
  'battleCell': Side3BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': SideCogParent3,
  'boss': 0,
  'level': 15,
  'battleCell': Side3BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}]
ReserveCogData = []
