from SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 10000
MidCogParent = 10022
BeginCogParent = 10040
FrontCogParent = 10060
BattleCellId = 0
MidBattleCellId = 1
BeginBattleCellId = 2
FrontBattleCellId = 3
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
 MidBattleCellId: {'parentEntId': MidCogParent,
                   'pos': Point3(0, 0, 0)},
 BeginBattleCellId: {'parentEntId': BeginCogParent,
                   'pos': Point3(0, 0, 0)},
 FrontBattleCellId: {'parentEntId': FrontCogParent,
                     'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'ad',
  'parentEntId': CogParent,
  'boss': 0,
  'level': 22,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'ls',
  'parentEntId': MidCogParent,
  'boss': 0,
  'level': 19,
  'battleCell': MidBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': MidBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'type': 'rb',
  'parentEntId': MidCogParent,
  'boss': 0,
  'level': 20,
  'battleCell': MidBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': MidBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'type': 'ad',
  'parentEntId': BeginCogParent,
  'boss': 0,
  'level': 22,
  'battleCell': BeginBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'type': 'ad',
  'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 22,
  'battleCell': FrontBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}]
ReserveCogData = []
