from SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 10000
MidCogParent = 10022
BeginCogParent = 10040
FrontCogParent = 10060
BattleCellId = 0
MidBattleCellId = 1
BeginBattleCellId = 2
FrontBattleCellId = 3
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
 MidBattleCellId: {'parentEntId': MidCogParent,
                   'pos': Point3(0, 0, 0)},
 BeginBattleCellId: {'parentEntId': BeginCogParent,
                   'pos': Point3(0, 0, 0)},
 FrontBattleCellId: {'parentEntId': FrontCogParent,
                     'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent,
  'boss': 0,
  'level': 15,
  'revives': random.choice([0, 1]),
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'revives': random.choice([0, 1]),
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 15,
  'revives': random.choice([0, 1]),
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'revives': random.choice([0, 1]),
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 15,
  'revives': random.choice([0, 1]),
  'battleCell': MidBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 16,
  'revives': random.choice([0, 1]),
  'battleCell': MidBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 14,
  'revives': random.choice([0, 1]),
  'battleCell': MidBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 16,
  'revives': random.choice([0, 1]),
  'battleCell': MidBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'revives': random.choice([0, 1, 2]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'revives': random.choice([0, 1, 2]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'revives': random.choice([0, 1, 2]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': BeginCogParent,
  'boss': 0,
  'level': random.choice([8, 9, 10, 11]),
  'revives': random.choice([0, 1, 2]),
  'battleCell': BeginBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 16,
  'revives': random.choice([0, 1]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 15,
  'revives': random.choice([0, 1]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 16,
  'revives': random.choice([0, 1]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 14,
  'revives': random.choice([0, 1]),
  'battleCell': FrontBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}]
ReserveCogData = []
