from toontown.toonbase import TTLocalizer
from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500.0,
        'modelFilename': 'phase_9/models/cogHQ/SelbotLegFactory'},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 3: {'type': 'zone',
     'name': 'Main Entrance',
     'comment': '',
     'parentEntId': 0,
     'scale': Vec3(1, 1, 1),
     'description': TTLocalizer.SellbotLegFactorySpecMainEntrance,
     'visibility': [114]},
 4: {'type': 'zone',
     'name': 'Lobby',
     'comment': '',
     'parentEntId': 0,
     'scale': Vec3(1, 1, 1),
     'description': TTLocalizer.SellbotLegFactorySpecLobby,
     'visibility': [113, 114]},
 5: {'type': 'zone',
     'name': 'hallwayFromLobby',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': [113, 116]},
 6: {'type': 'zone',
     'name': 'hallwayToBoiler/Control/Lookout',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': TTLocalizer.SellbotLegFactorySpecLobbyHallway,
     'visibility': [109,
                    116,
                    117,
                    118]},
 7: {'type': 'zone',
     'name': 'GearRoom',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': TTLocalizer.SellbotLegFactorySpecGearRoom,
     'visibility': [109, 110]},
 8: {'type': 'zone',
     'name': 'BoilerRoom',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': TTLocalizer.SellbotLegFactorySpecBoilerRoom,
     'visibility': [108, 117]},
 9: {'type': 'zone',
     'name': 'EastCatwalk',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': TTLocalizer.SellbotLegFactorySpecEastCatwalk,
     'visibility': [23,
                    25,
                    26,
                    33,
                    34,
                    35,
                    38,
                    41,
                    53,
                    110,
                    112,
                    115,
                    124,
                    200,
                    222]},
 10: {'type': 'zone',
      'name': 'PaintMixer',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecPaintMixer,
      'visibility': [11, 111, 112]},
 11: {'type': 'zone',
      'name': 'PaintMixerRewardRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecPaintMixerStorageRoom,
      'visibility': [10, 111, 112]},
 12: {'type': 'zone',
      'name': 'WestSiloCatwalk',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecWestSiloCatwalk,
      'visibility': [21,
                     26,
                     33,
                     34,
                     35,
                     36,
                     37,
                     40,
                     41,
                     53,
                     60,
                     61,
                     108,
                     110,
                     119,
                     120,
                     125,
                     127,
                     128,
                     129,
                     130,
                     200]},
 13: {'type': 'zone',
      'name': 'PipeRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecPipeRoom,
      'visibility': [119, 121]},
 14: {'type': 'zone',
      'name': 'StairsToPipeRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': [17,
                     18,
                     121,
                     126,
                     131]},
 15: {'type': 'zone',
      'name': 'DuctRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecDuctRoom,
      'visibility': [106, 126]},
 16: {'type': 'zone',
      'name': 'Side Entrance',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecSideEntrance,
      'visibility': [106]},
 17: {'type': 'zone',
      'name': 'StomperAlley',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecStomperAlley,
      'visibility': [14,
                     121,
                     126,
                     131]},
 18: {'type': 'zone',
      'name': 'LavaRoomFoyer',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecLavaRoomFoyer,
      'visibility': [19,
                     20,
                     102,
                     103,
                     105,
                     131]},
 19: {'type': 'zone',
      'name': 'LavaRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecLavaRoom,
      'visibility': [17,
                     18,
                     20,
                     105,
                     131]},
 20: {'type': 'zone',
      'name': 'LavaRewardRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecLavaStorageRoom,
      'visibility': [18, 19, 105]},
 21: {'type': 'zone',
      'name': 'WestCatwalk',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecWestCatwalk,
      'visibility': [12,
                     23,
                     26,
                     33,
                     34,
                     35,
                     40,
                     41,
                     53,
                     60,
                     108,
                     119,
                     120,
                     125,
                     127,
                     200]},
 22: {'type': 'zone',
      'name': 'OilRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecOilRoom,
      'visibility': [107]},
 23: {'type': 'zone',
      'name': 'Lookout',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecLookout,
      'visibility': [24,
                     39,
                     115,
                     118,
                     120,
                     123,
                     124,
                     125]},
 24: {'type': 'zone',
      'name': 'Warehouse',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecWarehouse,
      'visibility': [23,
                     39,
                     115,
                     120,
                     123,
                     124,
                     125]},
 25: {'type': 'zone',
      'name': 'PaintMixerExterior',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': []},
 26: {'type': 'zone',
      'name': 'WarehouseExterior',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': []},
 27: {'type': 'zone',
      'name': 'OilRoomHallway',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecOilRoomHallway,
      'visibility': [105, 107, 127]},
 30: {'type': 'zone',
      'name': 'EastSiloControlRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecEastSiloControlRoom,
      'visibility': [130]},
 31: {'type': 'zone',
      'name': 'WestSiloControlRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecWestSiloControlRoom,
      'visibility': [128]},
 32: {'type': 'zone',
      'name': 'CenterSiloControlRoom',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecCenterSiloControlRoom,
      'visibility': [129]},
 33: {'type': 'zone',
      'name': 'EastSilo',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecEastSilo,
      'visibility': [9,
                     12,
                     21,
                     25,
                     26,
                     34,
                     35,
                     36,
                     37,
                     38,
                     40,
                     41,
                     53,
                     60,
                     61,
                     108,
                     110,
                     112,
                     119,
                     124,
                     128,
                     129,
                     130,
                     200,
                     222]},
 34: {'type': 'zone',
      'name': 'WestSilo',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecWestSilo,
      'visibility': [9,
                     12,
                     21,
                     25,
                     26,
                     33,
                     35,
                     36,
                     37,
                     40,
                     41,
                     53,
                     60,
                     61,
                     108,
                     110,
                     112,
                     119,
                     120,
                     125,
                     127,
                     128,
                     129,
                     130,
                     200]},
 35: {'type': 'zone',
      'name': 'CenterSilo',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecCenterSilo,
      'visibility': [9,
                     21,
                     25,
                     26,
                     33,
                     34,
                     36,
                     37,
                     40,
                     41,
                     53,
                     60,
                     61,
                     108,
                     110,
                     112,
                     119,
                     128,
                     129,
                     130,
                     200]},
 36: {'type': 'zone',
      'name': 'WestSiloBridge',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': [9,
                     12,
                     21,
                     25,
                     26,
                     33,
                     34,
                     35,
                     36,
                     37,
                     40,
                     41,
                     53,
                     60,
                     61,
                     108,
                     110,
                     112,
                     119,
                     127,
                     128,
                     129,
                     130,
                     200]},
 37: {'type': 'zone',
      'name': 'EastSiloBridge',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': [9,
                     12,
                     21,
                     25,
                     26,
                     33,
                     34,
                     35,
                     36,
                     37,
                     38,
                     40,
                     41,
                     53,
                     60,
                     61,
                     108,
                     110,
                     112,
                     119,
                     128,
                     129,
                     130,
                     200,
                     222]},
 38: {'type': 'zone',
      'name': 'EastSiloCatwalk',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecEastSiloCatwalk,
      'visibility': [9,
                     25,
                     26,
                     33,
                     34,
                     35,
                     36,
                     37,
                     41,
                     53,
                     60,
                     110,
                     112,
                     115,
                     124,
                     200,
                     222]},
 39: {'type': 'zone',
      'name': 'WarehouseCeiling',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': []},
 40: {'type': 'zone',
      'name': 'WestExterior',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': []},
 41: {'type': 'zone',
      'name': 'EastExterior',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': []},
 53: {'type': 'zone',
      'name': 'ExteriorFloor',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': '',
      'visibility': []},
 60: {'type': 'zone',
      'name': 'WestElevatorShaft',
      'comment': '',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecWestElevatorShaft,
      'visibility': [12, 34]},
 61: {'type': 'zone',
      'name': 'EastElevatorShaft',
      'comment': 'no geom or DCS',
      'parentEntId': 0,
      'scale': 1,
      'description': TTLocalizer.SellbotLegFactorySpecEastElevatorShaft,
      'visibility': [33, 38]},
 101: {'type': 'zone',
       'name': 'dwToLavaRewardRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 102: {'type': 'zone',
       'name': 'dwToLavaRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 103: {'type': 'zone',
       'name': 'dwToLavaRoomHallway',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 105: {'type': 'zone',
       'name': 'dwToOilRoomCatwalks',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 106: {'type': 'zone',
       'name': 'dwToDuctRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 107: {'type': 'zone',
       'name': 'dwToOilRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 108: {'type': 'zone',
       'name': 'dwFromBoilerRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 109: {'type': 'zone',
       'name': 'dwToGearRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 110: {'type': 'zone',
       'name': 'dwFromGearRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 111: {'type': 'zone',
       'name': 'dwToPaintMixerRewardRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 112: {'type': 'zone',
       'name': 'dwToPaintMixer',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 113: {'type': 'zone',
       'name': 'dwFromLobby',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 114: {'type': 'zone',
       'name': 'dwToLobby',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 115: {'type': 'zone',
       'name': 'dwToWarehouseFromRight',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 116: {'type': 'zone',
       'name': 'dwFromLobbyFar',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 117: {'type': 'zone',
       'name': 'dwToBoilerRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 118: {'type': 'zone',
       'name': 'dwToLookout',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 119: {'type': 'zone',
       'name': 'dwFromPipeRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 120: {'type': 'zone',
       'name': 'dwToWarehouseFromLeft',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 121: {'type': 'zone',
       'name': 'dwToPipeRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 122: {'type': 'zone',
       'name': 'dwToWarehouseControlRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 123: {'type': 'zone',
       'name': 'dwFromWarehouseFloor',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 124: {'type': 'zone',
       'name': 'dwFromWarehouseRight',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 125: {'type': 'zone',
       'name': 'dwFromWarehouseLeft',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 126: {'type': 'zone',
       'name': 'dwFromDuctRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 127: {'type': 'zone',
       'name': 'dwFromOilRoomHallway',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 128: {'type': 'zone',
       'name': 'dwToWestSiloRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 129: {'type': 'zone',
       'name': 'dwToCenterSiloRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 130: {'type': 'zone',
       'name': 'dwToEastSiloRoom',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 131: {'type': 'zone',
       'name': 'dwFromStomperAlley',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 200: {'type': 'zone',
       'name': 'sky',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 201: {'type': 'zone',
       'name': 'extraZone201',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 202: {'type': 'zone',
       'name': 'extraZone202',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 203: {'type': 'zone',
       'name': 'extraZone203',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 204: {'type': 'zone',
       'name': 'extraZone204',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 205: {'type': 'zone',
       'name': 'extraZone205',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 206: {'type': 'zone',
       'name': 'extraZone206',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 207: {'type': 'zone',
       'name': 'extraZone207',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 208: {'type': 'zone',
       'name': 'extraZone208',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 209: {'type': 'zone',
       'name': 'extraZone209',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 210: {'type': 'zone',
       'name': 'extraZone210',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 211: {'type': 'zone',
       'name': 'extraZone211',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 212: {'type': 'zone',
       'name': 'extraZone212',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 213: {'type': 'zone',
       'name': 'extraZone213',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 214: {'type': 'zone',
       'name': 'extraZone214',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 215: {'type': 'zone',
       'name': 'extraZone215',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 216: {'type': 'zone',
       'name': 'extraZone216',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 217: {'type': 'zone',
       'name': 'extraZone217',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 218: {'type': 'zone',
       'name': 'extraZone218',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 219: {'type': 'zone',
       'name': 'extraZone219',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 220: {'type': 'zone',
       'name': 'extraZone220',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 221: {'type': 'zone',
       'name': 'extraZone221',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 222: {'type': 'zone',
       'name': 'dwToEastSiloInterior',
       'comment': '',
       'parentEntId': 0,
       'scale': 1,
       'description': '',
       'visibility': []},
 10010: {'type': 'ambientSound',
         'name': 'westWind',
         'comment': '',
         'parentEntId': 35,
         'pos': Point3(-52.7549, -38.8374, 53.3758),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'enabled': 1,
         'soundPath': 'phase_9/audio/sfx/CHQ_FACT_whistling_wind.ogg',
         'volume': 1},
 10016: {'type': 'ambientSound',
         'name': 'sndConveyorBelt',
         'comment': '',
         'parentEntId': 10056,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'enabled': 1,
         'soundPath': 'phase_9/audio/sfx/CHQ_FACT_conveyor_belt.ogg',
         'volume': 0.5},
 10053: {'type': 'ambientSound',
         'name': 'eastWind',
         'comment': '',
         'parentEntId': 35,
         'pos': Point3(52.75, -38.84, 53.38),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'enabled': 1,
         'soundPath': 'phase_9/audio/sfx/CHQ_FACT_whistling_wind.ogg',
         'volume': 1},
 10055: {'type': 'ambientSound',
         'name': 'sndGears',
         'comment': '',
         'parentEntId': 10056,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'enabled': 1,
         'soundPath': 'phase_9/audio/sfx/CHQ_FACT_gears_turning.ogg',
         'volume': 1},
 10031: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 8,
         'pos': Point3(-1, 79, 10),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1.75, 1, 1),
         'cellId': 1,
         'radius': 10.0},
 10035: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10039,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Vec3(1, 1, 1),
         'cellId': 4,
         'radius': 10.0},
 10038: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(0, -28.04, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(1, 1, 1),
         'cellId': 5,
         'radius': 10.0},
 20048: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0.973602, 71.7, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 0.2, 1),
         'cellId': 0,
         'radius': 15.0},
 20086: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 15,
         'pos': Point3(0, 33, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(2, 1, 1),
         'cellId': 6,
         'radius': 12.0},
 20112: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 33,
         'pos': Point3(-10.0936, -9.55975, 4),
         'hpr': Point3(45, 0, 0),
         'scale': Point3(10, 1, 5),
         'cellId': 10,
         'radius': 5.0},
 20113: {'type': 'battleBlocker',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 34,
         'pos': Point3(9.08399, 4.42157, 0),
         'hpr': Point3(-50, 0, 0),
         'scale': Point3(10, 2, 6),
         'cellId': 9,
         'radius': 5.0},
 10003: {'type': 'healBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20,
         'pos': Point3(1.25458, 19.2471, 0.0249529),
         'hpr': Vec3(-8.28434, 0, 0),
         'scale': 1,
         'rewardPerGrab': 20,
         'rewardPerGrabMax': 0},
 10011: {'type': 'beanBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20,
         'pos': Point3(16.344, -9.73, 0.025),
         'hpr': Vec3(-79.8888, 0, 0),
         'scale': 1,
         'rewardPerGrab': 150,
         'rewardPerGrabMax': 0},
 20017: {'type': 'healBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(20.0035, 2.94232, 0),
         'hpr': Vec3(-31.6033, 0, 0),
         'scale': 1,
         'rewardPerGrab': 20,
         'rewardPerGrabMax': 0},
 10005: {'type': 'conveyorBelt',
         'name': 'belt',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, 45.2024, 7.24937),
         'hpr': Point3(180, 0, 0),
         'scale': 1,
         'floorName': 'platformcollision',
         'length': 78.81881352704218,
         'speed': 2.0,
         'treadLength': 10.0,
         'treadModelPath': 'phase_9/models/cogHQ/platform1',
         'widthScale': 0.85},
 20081: {'type': 'crate',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20080,
         'pos': Point3(0, 0, 0),
         'scale': 0.920000016689,
         'crushCellId': None,
         'gridId': 20080,
         'modelType': 0,
         'pushable': 1},
 20091: {'type': 'crate',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20090,
         'pos': Point3(0, 23, 0),
         'scale': 0.920000016689,
         'crushCellId': None,
         'gridId': 20090,
         'modelType': 0,
         'pushable': 1},
 20024: {'type': 'crusherCell',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20023,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'col': 1,
         'gridId': 20025,
         'row': 14},
 20026: {'type': 'crusherCell',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20023,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'col': 10,
         'gridId': 20025,
         'row': 14},
 20027: {'type': 'crusherCell',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20023,
         'pos': Point3(1, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'col': 21,
         'gridId': 20025,
         'row': 14},
 20028: {'type': 'crusherCell',
         'name': 'copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20023,
         'pos': Point3(2, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'col': 28,
         'gridId': 20025,
         'row': 14},
 10049: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 3},
 10051: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 4},
 60000: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 5},
 60001: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 6},
 60002: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 7},
 60003: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 9},
 60004: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 10},
 60005: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 8},
 60006: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 21},
 60007: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 24},
 60009: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 38},
 60011: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 12},
 60013: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 13},
 60014: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 14},
 60015: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 17},
 60016: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 15},
 60017: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 16},
 60018: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 19},
 60019: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 18},
 60024: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 22},
 60031: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 23},
 60044: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 33},
 60066: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 11},
 60067: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 27},
 60096: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 30},
 60108: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 34},
 60111: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 36},
 60114: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 37},
 60121: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 31},
 60126: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 35},
 60130: {'type': 'entityGroup',
         'name': 'viz',
         'comment': '',
         'parentEntId': 32},
 10028: {'type': 'entrancePoint',
         'name': 'entrance1',
         'comment': '',
         'parentEntId': 3,
         'pos': Point3(0, 10, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'entranceId': 0,
         'radius': 15,
         'theta': 20},
 10029: {'type': 'entrancePoint',
         'name': 'entrance2',
         'comment': '',
         'parentEntId': 16,
         'pos': Point3(0, 10, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'entranceId': 1,
         'radius': 15,
         'theta': 20},
 10021: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(-2.02081, 0, 0),
         'hpr': Vec3(337.477, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10024: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(20.3012, -26.3219, 0),
         'hpr': Vec3(233.187, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10025: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(-47.312, 7.22571, 0),
         'hpr': Vec3(19.1524, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 10026: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10022,
         'pos': Point3(-11.2037, 5.43514, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 20020: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20,
         'pos': Point3(-23.0209, 0, 0),
         'hpr': Vec3(126.676, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 20021: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20,
         'pos': Point3(-31.3225, 14.1021, 0),
         'hpr': Vec3(-136.57, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 20085: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 5,
         'pos': Point3(3.14, 12.6703, 10.12),
         'hpr': Vec3(-24.8105, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 10,
         'rewardPerGrabMax': 0},
 20093: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20087,
         'pos': Point3(2.4, -1, 7),
         'hpr': Vec3(-151.532, 0, 0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 0},
 10006: {'type': 'gear',
         'name': 'first',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(0, 0, 26.0634),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'degreesPerSec': 20.0,
         'gearScale': 25.0,
         'modelType': 'factory',
         'orientation': 'vertical',
         'phaseShift': 0},
 10007: {'type': 'gear',
         'name': 'second',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(0, 15, 26.06),
         'hpr': Point3(180, 0, 0),
         'scale': 1,
         'degreesPerSec': 30.0,
         'gearScale': 25.0,
         'modelType': 'factory',
         'orientation': 'vertical',
         'phaseShift': 0},
 10008: {'type': 'gear',
         'name': 'third',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(0, 30, 26.06),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'degreesPerSec': 40.0,
         'gearScale': 25.0,
         'modelType': 'factory',
         'orientation': 'vertical',
         'phaseShift': 0},
 10009: {'type': 'gear',
         'name': 'fourth',
         'comment': '',
         'parentEntId': 10004,
         'pos': Point3(0, 45, 26.06),
         'hpr': Point3(180, 0, 0),
         'scale': 1,
         'degreesPerSec': 47.0,
         'gearScale': 25.0,
         'modelType': 'factory',
         'orientation': 'vertical',
         'phaseShift': 0},
 20013: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20012,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.25,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6},
 20014: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20010,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.25,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6},
 20016: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20015,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.25,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6},
 20041: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20040,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20026,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 80.0,
         'strength': 75,
         'velocity': 6.0},
 20043: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20042,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20024,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 80.0,
         'strength': 75,
         'velocity': 5.0},
 20046: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20044,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20024,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 70,
         'strength': 75,
         'velocity': 6.0},
 20047: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20045,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20026,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 80.0,
         'strength': 75,
         'velocity': 6.0},
 20052: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20051,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 12.0,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6.0},
 20054: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20053,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20027,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 80.0,
         'strength': 75,
         'velocity': 6.0},
 20056: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20055,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20028,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 70,
         'strength': 75,
         'velocity': 6.0},
 20060: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20059,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20028,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 90.0,
         'strength': 75,
         'velocity': 6.0},
 20062: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20061,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': 20027,
         'goonType': 'pg',
         'gridId': 20025,
         'hFov': 70,
         'strength': 75,
         'velocity': 6.0},
 20071: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20070,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6.0},
 20072: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20069,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 80.0,
         'strength': 75,
         'velocity': 6.0},
 20074: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20073,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.25,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6},
 20089: {'type': 'goon',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20084,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1.5,
         'attackRadius': 15,
         'crushCellId': None,
         'goonType': 'pg',
         'gridId': None,
         'hFov': 70,
         'strength': 75,
         'velocity': 6},
 20115: {'type': 'goonClipPlane',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, -7.4, 0),
         'hpr': Point3(-90, 0, 0),
         'scale': Point3(5, 5, 5),
         'goonId': 20052},
 20116: {'type': 'goonClipPlane',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, -58, 0),
         'hpr': Point3(90, 0, 0),
         'scale': 1,
         'goonId': None},
 20117: {'type': 'goonClipPlane',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(0, -29, 0),
         'hpr': Point3(90, 0, 0),
         'scale': 1,
         'goonId': None},
 20118: {'type': 'goonClipPlane',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(-52, 0, 5),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'goonId': None},
 20025: {'type': 'grid',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20023,
         'pos': Point3(-48.4442, -24.9385, 0),
         'scale': 1,
         'cellSize': 3,
         'numCol': 30,
         'numRow': 16},
 20080: {'type': 'grid',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 5,
         'pos': Point3(1.5, -10.7, 0),
         'scale': 1,
         'cellSize': 3,
         'numCol': 2,
         'numRow': 5},
 20090: {'type': 'grid',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 17,
         'pos': Point3(-6.5, -111, 0),
         'scale': 1,
         'cellSize': 3,
         'numCol': 2,
         'numRow': 9},
 20011: {'type': 'healBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20,
         'pos': Point3(-2.06235, 20.2198, 0.025),
         'hpr': Vec3(-19.2153, 0, 0),
         'scale': 1,
         'rewardPerGrab': 30,
         'rewardPerGrabMax': 0},
 20092: {'type': 'healBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20087,
         'pos': Point3(-1, -1.5, 7),
         'hpr': Vec3(-191.79, 0, 0),
         'scale': 1,
         'rewardPerGrab': 20,
         'rewardPerGrabMax': 0},
 10041: {'type': 'lift',
         'name': 'westLift',
         'comment': '',
         'parentEntId': 60,
         'pos': Point3(0, 0, 0.0641994),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'autoMoveDelay': 5,
         'duration': 7.0,
         'endBoardSides': ['back'],
         'endGuardName': 'topGuard',
         'endPos': Point3(0, 0, 165),
         'floorName': 'elevator_floor',
         'modelPath': 'phase_9/models/cogHQ/Elevator.bam',
         'modelScale': Vec3(1, 1, 1),
         'moveDelay': 1,
         'startBoardSides': ['front'],
         'startGuardName': 'bottomGuard',
         'startPos': Point3(0, 0, 0)},
 10048: {'type': 'lift',
         'name': 'eastLift',
         'comment': '',
         'parentEntId': 61,
         'pos': Point3(0, -0.684064, 0.589322),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'autoMoveDelay': 5.0,
         'duration': 7.0,
         'endBoardSides': ['front',
                           'back',
                           'left',
                           'right'],
         'endGuardName': 'topGuard',
         'endPos': Point3(0, 0, 165),
         'floorName': 'elevator_floor',
         'modelPath': 'phase_9/models/cogHQ/Elevator.bam',
         'modelScale': Vec3(1, 1, 1),
         'moveDelay': 1,
         'startBoardSides': ['front'],
         'startGuardName': 'bottomGuard',
         'startPos': Point3(0, 0, 0)},
 10001: {'type': 'model',
         'name': 'dropshadow',
         'comment': '',
         'parentEntId': 10006,
         'pos': Point3(0, 0, -25),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(2, 1.5, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_3/models/props/drop_shadow.bam'},
 10012: {'type': 'model',
         'name': 'backCrate',
         'comment': '',
         'parentEntId': 10067,
         'pos': Point3(0, -5.81496, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 10033: {'type': 'model',
         'name': 'dropshadow',
         'comment': '',
         'parentEntId': 10007,
         'pos': Point3(0, 0, -25),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(2, 1.5, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_3/models/props/drop_shadow.bam'},
 10045: {'type': 'model',
         'name': 'dropshadow',
         'comment': '',
         'parentEntId': 10008,
         'pos': Point3(0, 0, -25),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(2, 1.5, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_3/models/props/drop_shadow.bam'},
 10046: {'type': 'model',
         'name': 'dropshadow',
         'comment': '',
         'parentEntId': 10009,
         'pos': Point3(0, 0, -25),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(2, 1.5, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_3/models/props/drop_shadow.bam'},
 10050: {'type': 'model',
         'name': 'sky',
         'comment': '',
         'parentEntId': 200,
         'pos': Point3(-142.02, 437.227, 0.922491),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(2.5, 2.5, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/cog_sky.bam'},
 10066: {'type': 'model',
         'name': 'frontCrate',
         'comment': '',
         'parentEntId': 10067,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 10069: {'type': 'model',
         'name': 'backCrate',
         'comment': '',
         'parentEntId': 10065,
         'pos': Point3(0, -5.81496, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 2),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 10070: {'type': 'model',
         'name': 'frontCrate',
         'comment': '',
         'parentEntId': 10065,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 20082: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 5,
         'pos': Point3(4.50815, 11.6508, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(0.92, 0.92, 0.92),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 20083: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20082,
         'pos': Point3(0, 0, 5.5),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 20088: {'type': 'model',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20087,
         'pos': Point3(1, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1.3, 1, 1.3),
         'collisionsOnly': 0,
         'flattenType': 'light',
         'loadType': 'loadModelCopy',
         'modelPath': 'phase_9/models/cogHQ/metal_crateB.bam'},
 10000: {'type': 'nodepath',
         'name': 'gearGauntletObstacle',
         'comment': '',
         'parentEntId': 10027,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10004: {'type': 'nodepath',
         'name': 'gearGauntlet',
         'comment': 'gears are staggered 15 ft in Y',
         'parentEntId': 10000,
         'pos': Point3(0, -23.25, 6.85),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10010: {'type': 'nodepath',
         'name': 'frontCogs',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, 50.07, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10011: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, 34.07, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10012: {'type': 'nodepath',
         'name': 'cogs2',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, -25.0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10013: {'type': 'nodepath',
         'name': 'frontCogs',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, 50.07, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10015: {'type': 'nodepath',
         'name': 'paint mixer platforms',
         'comment': '',
         'parentEntId': 10,
         'pos': Point3(0, 5.15136, -8),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10022: {'type': 'nodepath',
         'name': 'gagBarrels',
         'comment': '',
         'parentEntId': 11,
         'pos': Point3(11.2328, 14.7959, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10023: {'type': 'nodepath',
         'name': 'leftCogs',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(-42.0363, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10024: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0.0, 100, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10027: {'type': 'nodepath',
         'name': 'zoneNodeCompensate',
         'comment': 'I think the ZoneNode was moved.',
         'parentEntId': 19,
         'pos': Point3(-0.426482, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10028: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 8,
         'pos': Point3(-50.5, 0.0, 0),
         'hpr': Point3(90, 0, 0),
         'scale': 1},
 10029: {'type': 'nodepath',
         'name': 'cogs1',
         'comment': '',
         'parentEntId': 8,
         'pos': Point3(0.0, 2.5, 0),
         'hpr': Point3(90, 0, 0),
         'scale': 1},
 10030: {'type': 'nodepath',
         'name': 'cogs2',
         'comment': '',
         'parentEntId': 8,
         'pos': Point3(2.5, 62.5, 10),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10032: {'type': 'nodepath',
         'name': 'rightCogs',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(46.88, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10033: {'type': 'nodepath',
         'name': 'cogs2',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0.0, -100, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10034: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 22,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(180, 0, 0),
         'scale': 1},
 10036: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 15,
         'pos': Point3(5.5, 0, 0),
         'hpr': Point3(161, 0, 0),
         'scale': 1},
 10037: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(3.1, -48.27, 0.05),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10038: {'type': 'nodepath',
         'name': 'cogs1',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(1.5, 25.0, 0.05),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10039: {'type': 'nodepath',
         'name': 'cogs2',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(-50.5, -15.0, 10.05),
         'hpr': Point3(180, 0, 0),
         'scale': 1},
 10041: {'type': 'nodepath',
         'name': 'cogs3',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(1.5, 45.0, 0.05),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 10040: {'type': 'nodepath',
         'name': 'FactoryBoss',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(0, 68.4457, 9.5669),
         'hpr': Point3(180, 0, 0),
         'scale': 1},
 10047: {'type': 'nodepath',
         'name': 'battleCell',
         'comment': '',
         'parentEntId': 34,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10056: {'type': 'nodepath',
         'name': 'sounds',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, 0, 15),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10064: {'type': 'nodepath',
         'name': 'battleCell',
         'comment': '',
         'parentEntId': 32,
         'pos': Point3(0, -5.20447, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10065: {'type': 'nodepath',
         'name': 'backSteps',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, 56.2652, 0),
         'hpr': Point3(0, 0, 0),
         'scale': Point3(1.5, 1.3, 0.73)},
 10067: {'type': 'nodepath',
         'name': 'frontSteps',
         'comment': '',
         'parentEntId': 10000,
         'pos': Point3(0, -44.7196, 0),
         'hpr': Point3(180, 0, 0),
         'scale': Point3(1.5, 1.3, 0.729057)},
 10068: {'type': 'nodepath',
         'name': 'battleCell',
         'comment': '',
         'parentEntId': 33,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20000: {'type': 'nodepath',
         'name': 'stompers',
         'comment': '',
         'parentEntId': 17,
         'pos': Point3(0.75, 0, 0.5),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20016: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10010,
         'pos': Point3(0, -24, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20017: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10011,
         'pos': Point3(0, -24, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20018: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 10012,
         'pos': Point3(0, -24, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20019: {'type': 'nodepath',
         'name': 'cogsJoin',
         'comment': '',
         'parentEntId': 10028,
         'pos': Point3(16, 2, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20020: {'type': 'nodepath',
         'name': 'cogsJoin',
         'comment': '',
         'parentEntId': 10029,
         'pos': Point3(16, 2, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20021: {'type': 'nodepath',
         'name': 'cogsJoin',
         'comment': '',
         'parentEntId': 10030,
         'pos': Point3(16, 2, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20022: {'type': 'nodepath',
         'name': 'StomperButtonsNodepath',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(-11.75, -35.8, 14.9),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20023: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20037: {'type': 'nodepath',
         'name': 'SignatureGoonNP',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(-48.4442, -24.9385, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20058: {'type': 'nodepath',
         'name': 'SigRoomCogs',
         'comment': '',
         'parentEntId': 24,
         'pos': Point3(-1.0928, -45, 14.99),
         'hpr': Point3(90, 0, 0),
         'scale': 1},
 20087: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 17,
         'pos': Point3(-4, -117, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20094: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 34,
         'pos': Point3(-0.720506, 27.5461, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20095: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 32,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1},
 20096: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 33,
         'pos': Point3(4.84921, 8.74482, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 10017: {'type': 'paintMixer',
         'name': 'fifth',
         'comment': '',
         'parentEntId': 10015,
         'pos': Point3(5.24, 23.52, 8),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'floorName': 'PaintMixerFloorCollision',
         'modelPath': 'phase_9/models/cogHQ/PaintMixer',
         'modelScale': Point3(0.8, 0.8, 0.8),
         'motion': 'easeInOut',
         'offset': Point3(-12, -6, 0),
         'period': 8.0,
         'phaseShift': 0.5,
         'shaftScale': 1,
         'waitPercent': 0.1},
 10018: {'type': 'paintMixer',
         'name': 'fourth',
         'comment': '',
         'parentEntId': 10015,
         'pos': Point3(-12.1, 3, 8),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'floorName': 'PaintMixerFloorCollision',
         'modelPath': 'phase_9/models/cogHQ/PaintMixer',
         'modelScale': Point3(0.8, 0.8, 0.8),
         'motion': 'easeInOut',
         'offset': Point3(0, -6, 15),
         'period': 8.0,
         'phaseShift': 0.0,
         'shaftScale': 2.5,
         'waitPercent': 0.1},
 10019: {'type': 'paintMixer',
         'name': 'third',
         'comment': '',
         'parentEntId': 10015,
         'pos': Point3(-3.85419, -7.75751, 22.5836),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'floorName': 'PaintMixerFloorCollision',
         'modelPath': 'phase_9/models/cogHQ/PaintMixer',
         'modelScale': Point3(0.8, 0.8, 0.8),
         'motion': 'easeInOut',
         'offset': Point3(7, 0, 0),
         'period': 8.0,
         'phaseShift': 0.0,
         'shaftScale': 2.5,
         'waitPercent': 0.1},
 10020: {'type': 'paintMixer',
         'name': 'second',
         'comment': '',
         'parentEntId': 10015,
         'pos': Point3(16.01, -6.47, 23),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'floorName': 'PaintMixerFloorCollision',
         'modelPath': 'phase_9/models/cogHQ/PaintMixer',
         'modelScale': Point3(0.8, 0.8, 0.8),
         'motion': 'easeInOut',
         'offset': Point3(-4, -8, -15),
         'period': 8.0,
         'phaseShift': 0.0,
         'shaftScale': 2.5,
         'waitPercent': 0.1},
 10054: {'type': 'paintMixer',
         'name': 'first',
         'comment': '',
         'parentEntId': 10015,
         'pos': Point3(-10, -26.1, 8),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'floorName': 'PaintMixerFloorCollision',
         'modelPath': 'phase_9/models/cogHQ/PaintMixer',
         'modelScale': Point3(0.8, 0.8, 0.8),
         'motion': 'easeInOut',
         'offset': Point3(15, 0, 0),
         'period': 8.0,
         'phaseShift': 0.0,
         'shaftScale': 1,
         'waitPercent': 0.1},
 20008: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 20009: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 17,
         'pathScale': 1.0},
 20010: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 21,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 36,
         'pathScale': 1.0},
 20012: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 21,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 34,
         'pathScale': 1.0},
 20015: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 21,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 37,
         'pathScale': 1.0},
 20038: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 15,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 38,
         'pathScale': 1.0},
 20039: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 12,
         'pathScale': 1.0},
 20040: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(41.5, 33.5, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 20042: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(15, 34, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 20044: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(1.5, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Vec3(1, 1, 1),
         'pathIndex': 6,
         'pathScale': 1.0},
 20045: {'type': 'path',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'pathIndex': 7,
         'pathScale': 1.0},
 20049: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 13,
         'pathScale': 1.0},
 20051: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(1, -24, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 42,
         'pathScale': 1.0},
 20053: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 8,
         'pathScale': 1.0},
 20055: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 9,
         'pathScale': 1.0},
 20059: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 10,
         'pathScale': 1.0},
 20061: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20037,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 11,
         'pathScale': 1.0},
 20067: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 15,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 39,
         'pathScale': 1.0},
 20068: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 15,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 40,
         'pathScale': 1.0},
 20069: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 9,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 5,
         'pathScale': 1.0},
 20070: {'type': 'path',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 9,
         'pos': Point3(1, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 5,
         'pathScale': 1.0},
 20073: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 21,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 35,
         'pathScale': 1.0},
 20075: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 7,
         'pos': Point3(4, 4, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 14,
         'pathScale': 1.0},
 20076: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 8,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 15,
         'pathScale': 1.0},
 20077: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 8,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 16,
         'pathScale': 1.0},
 20078: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 18,
         'pathScale': 1.0},
 20079: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 4,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 20084: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 9,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 41,
         'pathScale': 1.0},
 20097: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 34,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 19,
         'pathScale': 1.0},
 20098: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 34,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 20,
         'pathScale': 1.0},
 20099: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 34,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 21,
         'pathScale': 1.0},
 20100: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 33,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 22,
         'pathScale': 1.0},
 20101: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 33,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 23,
         'pathScale': 1.0},
 20102: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 33,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 24,
         'pathScale': 1.0},
 20103: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 32,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 25,
         'pathScale': 1.0},
 20104: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 32,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 26,
         'pathScale': 1.0},
 20105: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 32,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 27,
         'pathScale': 1.0},
 20106: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 28,
         'pathScale': 1.0},
 20107: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 29,
         'pathScale': 1.0},
 20108: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 30,
         'pathScale': 1.0},
 20109: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 31,
         'pathScale': 1.0},
 20110: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 32,
         'pathScale': 1.0},
 20111: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 13,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 33,
         'pathScale': 1.0},
 60133: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 22,
         'pos': Point3(-10, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 60134: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 22,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 60135: {'type': 'path',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 22,
         'pos': Point3(10, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'pathIndex': 0,
         'pathScale': 1.0},
 10042: {'type': 'propSpinner',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 7},
 20001: {'type': 'stomper',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(7, 5, 7),
         'modelPath': 0,
         'motion': 3,
         'period': 4.0,
         'phaseShift': 0.0,
         'range': 30.0,
         'shaftScale': Point3(0.5, 12, 0.5),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20002: {'type': 'stomper',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(0, -14.3294, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(7, 5, 7),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 10.0,
         'shaftScale': Point3(0.5, 12, 0.5),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20003: {'type': 'stomper',
         'name': 'copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(0, -28.3252, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(7, 5, 7),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.5,
         'range': 10.0,
         'shaftScale': Point3(0.5, 12, 0.5),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20004: {'type': 'stomper',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(-3.5, 16.2588, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 3,
         'period': 3.0001373423482587,
         'phaseShift': 0.0,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20005: {'type': 'stomper',
         'name': 'copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(3.5, 16.2588, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 3,
         'period': 1.5,
         'phaseShift': 0.0,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 1,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20006: {'type': 'stomper',
         'name': 'copy of copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(-3.5, 23.4392, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 3,
         'period': 1.5,
         'phaseShift': 0.5,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20007: {'type': 'stomper',
         'name': 'copy of copy of copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(3.5, 23.4392, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 30,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 3,
         'period': 3.0,
         'phaseShift': 0.5,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20029: {'type': 'stomper',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20025,
         'pos': Point3(4.5, 43.5, 0.25),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'animateShadow': 0,
         'crushCellId': 20024,
         'damage': 30,
         'headScale': Point3(3, 2, 3),
         'modelPath': 0,
         'motion': 5,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 12.0,
         'shaftScale': Point3(0.66, 37.5, 0.66),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 20033,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20030: {'type': 'stomper',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20025,
         'pos': Point3(31.5, 43.5, 0.25),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'animateShadow': 0,
         'crushCellId': 20026,
         'damage': 30,
         'headScale': Point3(3, 2, 3),
         'modelPath': 0,
         'motion': 5,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 12.0,
         'shaftScale': Point3(0.66, 37.5, 0.66),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 20034,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20031: {'type': 'stomper',
         'name': 'copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20025,
         'pos': Point3(64.5, 43.5, 0.25),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'animateShadow': 0,
         'crushCellId': 20027,
         'damage': 30,
         'headScale': Point3(3, 2, 3),
         'modelPath': 0,
         'motion': 5,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 12.0,
         'shaftScale': Point3(0.66, 37.5, 0.66),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 20035,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20032: {'type': 'stomper',
         'name': 'copy of copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20025,
         'pos': Point3(85.5, 43.5, 0.25),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'animateShadow': 0,
         'crushCellId': 20028,
         'damage': 30,
         'headScale': Point3(3, 2, 3),
         'modelPath': 0,
         'motion': 5,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 12.0,
         'shaftScale': Point3(0.66, 37.5, 0.66),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 20036,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20050: {'type': 'trigger',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20022,
         'pos': Point3(10, 0, 10),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(20, 20, 20),
         'isOn': 0,
         'isOnEvent': 0,
         'secondsOn': 1,
         'triggerName': 'signatureRoomView'},
 20057: {'type': 'trigger',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 23,
         'pos': Point3(3, -8.8, 15.5091),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(25, 25, 25),
         'isOn': 0,
         'isOnEvent': 0,
         'secondsOn': 1,
         'triggerName': 'lookoutTrigger'},
 30077: {'type': 'trigger',
         'name': 'button cutscene',
         'comment': '',
         'parentEntId': 3,
         'pos': Point3(-4, 8, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': Point3(1, 1, 1),
         'isOn': 0,
         'isOnEvent': 0,
         'secondsOn': 1,
         'triggerName': ''}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
